name: auto-approve-offset
image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: auto-approve-offset-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 3000
env:
  - name: "PORT"
    value: "3000"
  - name: "AUTHORIZATION"
    value: "<path:${vault_mount}/data/auto-approve-offset#AUTHORIZATION>"
  - name: "BLOCKSYNC_GRAPHQL"
    value: "<path:${vault_mount}/data/auto-approve-offset#BLOCKSYNC_GRAPHQL>"
  - name: "RPC_URL"
    value: "${rpc_url}"
  - name: "MNEMONIC_DELEGATE"
    value: "<path:${vault_mount}/data/auto-approve-offset#MNEMONIC_DELEGATE>"
  - name: "MNEMONIC_OWNER"
    value: "<path:${vault_mount}/data/auto-approve-offset#MNEMONIC_OWNER>"
  - name: "NETWORK"
    value: "${environment}"
  - name: "COLLECTION_IDS"
    value: "<path:${vault_mount}/data/auto-approve-offset#COLLECTION_IDS>"
  - name: "QUOTAS_PER_COLLECTION"
    value: "<path:${vault_mount}/data/auto-approve-offset#QUOTAS_PER_COLLECTION>"
  - name: "EXPIRATION_PER_COLLECTION"
    value: "<path:${vault_mount}/data/auto-approve-offset#EXPIRATION_PER_COLLECTION>"
  - name: "NOTIFICATIONS_WORKER_URL"
    value: "https://notifications.ixo.earth"
  - name: "NOTIFICATIONS_WORKER_AUTH"
    value: "<path:${vault_mount}/data/auto-approve-offset#NOTIFICATIONS_WORKER_AUTH>"
  - name: "NOTIFICATIONS_TEMPLATE_ID"
    value: "<path:${vault_mount}/data/auto-approve-offset#NOTIFICATIONS_TEMPLATE_ID>"
  - name: "NOTIFICATIONS_TEMPLATE_IDS"
    value: "<path:${vault_mount}/data/auto-approve-offset#NOTIFICATIONS_TEMPLATE_IDS>"
resources:
  requests:
    memory: 200Mi
    cpu: "40m"
  limits:
    memory: 300Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"