name: claims-credentials-claimformprotocol
image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: claims-credentials-claimformprotocol-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 3000
env:
  - name: "PORT"
    value: "3000"
  - name: "AUTHORIZATION"
    value: "<path:${vault_mount}/data/claims-credentials-claimformprotocol#AUTHORIZATION>"
  - name: "ENABLE_CLAIMS"
    value: "false"
  - name: "BLOCKSYNC_GRAPHQL"
    value: "http://ixo-blocksync.core.svc.cluster.local:8082"
  - name: "CELLNODE"
    value: "${cellnode}"
  - name: "RPC_URL"
    value: "${rpc_url}"
  - name: "SECP_MNEMONIC"
    value: "<path:${vault_mount}/data/claims-credentials-claimformprotocol#SECP_MNEMONIC>"
  - name: "ENABLE_CREDENTIALS"
    value: "true"
  - name: "ISSUER_DID"
    value: "<path:${vault_mount}/data/claims-credentials-claimformprotocol#ISSUER_DID>"
  - name: "CREDENTIALS_MNEMONIC"
    value: "<path:${vault_mount}/data/claims-credentials-claimformprotocol#CREDENTIALS_MNEMONIC>"
  - name: "NETWORK"
    value: ${environment}
  - name: "REMOTE_CONTEXTS"
    value: "[\"https://w3id.org/ixo/context/v1\"]"
  - name: "ENABLE_TOKENS"
    value: "false"
  - name: "ENABLE_PROOFS"
    value: "true"
  - name: "PROOFS_MNEMONIC"
    value: "<path:${vault_mount}/data/claims-credentials-claimformprotocol#PROOFS_MNEMONIC>"
  - name: "PROOFS_CONTROLLER"
    value: "<path:${vault_mount}/data/claims-credentials-claimformprotocol#PROOFS_CONTROLLER>"
resources:
  requests:
    memory: 200Mi
    cpu: "100m"
  limits:
    memory: 300Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"