name: claims-credentials-ecs
image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ecs-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 3000
env:
  - name: "PORT"
    value: "3000"
  - name: "Authorization"
    value: "<path:${vault_mount}/data/claims-credentials-ecs#AUTHORIZATION>"
  - name: "ENABLE_CLAIMS"
    value: "true"
  - name: "BLOCKSYNC_GRAPHQL"
    value: "http://ixo-blocksync.core.svc.cluster.local"
  - name: "CELLNODE"
    value: "http://ixo-cellnode.core.svc.cluster.local"
  - name: "RPC_URL"
    value: "https://devnet.ixo.earth/rpc/"
  - name: "SECP_MNEMONIC"
    value: "<path:${vault_mount}/data/claims-credentials-ecs#SECP_MNEMONIC>"
  - name: "ENABLE_CREDENTIALS"
    value: "true"
  - name: "ISSUER_DID"
    value: "<path:${vault_mount}/data/claims-credentials-ecs#ISSUER_DID>"
  - name: "CREDENTIALS_MNEMONIC"
    value: "<path:${vault_mount}/data/claims-credentials-ecs#CREDENTIALS_MNEMONIC>"
  - name: "NETWORK"
    value: ${environment}
  - name: "REMOTE_CONTEXTS"
    value: "[\"https://w3id.org/ixo/context/v1\"]"
  - name: "ENABLE_TOKENS"
    value: "false"
  - name: "ENABLE_PROOFS"
    value: "false"
resources:
  requests:
    memory: 200Mi
    cpu: "100m"
  limits:
    memory: 300Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"