image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
persistentVolume:
  storageClass: ${storage_class}
  size: ${storage_size}
service:
  port: 8081
env:
  - name: "PORT"
    value: "8081"
resources:
  requests:
    memory: 150Mi
    cpu: "40m"
  limits:
    memory: 300Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"
backup:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi
  gcs:
    bucket: ${gcs_bucket}
config:
  homeserverUrl: https://matrix.emediaworkspace.org
  homeserverName: matrix.emediaworkspace.org
  userCreation:
    registrationToken: "<path:${vault_mount}/data/matrix#MATRIX_DIGIHUB_APPSERVICE_ROOMS_USER_CREATION_REGISTRATION_TOKEN>"
  ucan:
    hostname: rooms.bot.matrix.emediaworkspace.org
    mnemonic: "<path:ixo_core/data/matrix#MATRIX_DIGIHUB_APPSERVICE_ROOMS_MNEMONIC>"
registration:
  hs_token: "<path:${vault_mount}/data/matrix#MATRIX_DIGIHUB_APPSERVICE_ROOMS_HS_TOKEN>"
  as_token: "<path:${vault_mount}/data/matrix#MATRIX_DIGIHUB_APPSERVICE_ROOMS_AS_TOKEN>"
  url: https://rooms.bot.matrix.emediaworkspace.org
  namespaces:
    aliases:
      - exclusive: true
        regex: "#did-ixo-.*"
      - exclusive: true
        regex: "#ixo-room-bot-signature-hashes*"
      - exclusive: true
        regex: "#ixo.*-pod"
    users:
      - exclusive: true
        regex: "@ixo-room-bot:matrix.emediaworkspace.org"
    rooms: []
