image:
  repository: ghcr.io/ixofoundation/ixo-terra-infra/hermes
  pullPolicy: Always
resources:
  requests:
    memory: 200Mi
    cpu: "50m"
  limits:
    memory: 350Mi
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-hermes-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix