image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    acme.cert-manager.io/http01-edit-in-place: "true"
  tls:
    - hosts:
        - ${host}
      secretName: ixo-blocksync-api-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 8081
%{ if eso_enabled ~}
externalSecret:
  enabled: true
  vaultPath: ixo-blocksync
%{ endif ~}
env:
  - name: "PORT"
    value: "8081"
  - name: "NODE_ENV"
    value: "production"
%{ if !eso_enabled ~}
  - name: "RPC"
    value: "<path:${vault_mount}/data/ixo-blocksync#RPC>"
%{ endif ~}
  - name: "DATABASE_USE_SSL"
    value: "1"
%{ if !eso_enabled ~}
  - name: "DATABASE_URL"
    value: "<path:${vault_mount}/data/ixo-blocksync#DATABASE_URL>"
  - name: "BLOCK_CACHE_LISTEN_DATABASE_URL"
    value: "<path:${vault_mount}/data/ixo-blocksync#BLOCK_CACHE_LISTEN_DATABASE_URL>"
%{ endif ~}
  - name: "IPFS_SERVICE_MAPPING"
    value: "${ipfs_service_mapping}"
%{ if !eso_enabled ~}
  - name: "CORE_DATABASE_URL"
    value: "<path:${vault_mount}/data/ixo-blocksync#CORE_DATABASE_URL>"
%{ endif ~}
resources:
  requests:
    memory: 1.8Gi
    cpu: "500m"
  limits:
    memory: 2Gi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"
verticalPodAutoscaler:
  enabled: true
  updateMode: "Off"