image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-notification-server-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
env:
  - name: "PORT"
    value: "3000"
  - name: "NODE_ENV"
    value: "production"
  - name: "AUTHORIZATION"
    value: "<path:${vault_mount}/data/ixo-notification-server#AUTHORIZATION>"
  - name: "AIRTABLE_API_KEY"
    value: "<path:${vault_mount}/data/ixo-notification-server#AIRTABLE_API_KEY>"
  - name: "AIRTABLE_BASE_ID"
    value: "<path:${vault_mount}/data/ixo-notification-server#AIRTABLE_BASE_ID>"
  - name: "AIRTABLE_TABLE_NOTIFICATIONS_V2"
    value: "<path:${vault_mount}/data/ixo-notification-server#AIRTABLE_TABLE_NOTIFICATIONS_V2>"
  - name: "PUBLIC_AUTHORIZATION"
    value: "<path:${vault_mount}/data/ixo-notification-server#PUBLIC_AUTHORIZATION>"
  - name: "MIGRATE_DB_PROGRAMATICALLY"
    value: "1"
  - name: "DATABASE_USE_SSL"
    value: "1"
  - name: "DATABASE_URL"
    value: "postgresql://${pgUsername}:${pgPassword}@${pgCluster}-primary.${pgNamespace}.svc.cluster.local/${pgUsername}"
service:
  port: 3000
resources:
  requests:
    memory: 200Mi
    cpu: "50m"
  limits:
    memory: 350Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"