image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-blocksync-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 8082
env:
  - name: "PORT"
    value: "8082"
  - name: "NODE_ENV"
    value: "production"
  - name: "RPC"
    value: "${rpc_url}"
  - name: "MIGRATE_DB_PROGRAMATICALLY"
    value: "1"
  - name: "DATABASE_USE_SSL"
    value: "1"
  - name: "IPFS_SERVICE_MAPPING"
    value: "${ipfs_service_mapping}"
  - name: "DATABASE_URL_CORE"
    value: "postgresql://${pgUsername_core}:${pgPassword_core}@${pgCluster}-primary.${pgNamespace}.svc.cluster.local/${pgUsername_core}"
  - name: "DATABASE_URL"
    value: "<path:${vault_mount}/data/ixo-blocksync#DATABASE_URL>"
  - name: "ENTITY_MODULE_CONTRACT_ADDRESS"
    value: "<path:${vault_mount}/data/ixo-blocksync#ENTITY_MODULE_CONTRACT_ADDRESS>"
resources:
  requests:
    memory: 1Gi
    cpu: "800m"
  limits:
    memory: 2Gi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"