image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-blocksync-core-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 8081
env:
  - name: "PORT"
    value: "8081"
  - name: "NODE_ENV"
    value: "production"
  - name: "TRUST_PROXY"
    value: "1"
  - name: "RPC"
    value: "${rpc_url}"
  - name: "MIGRATE_DB_PROGRAMATICALLY"
    value: "1"
  - name: "DATABASE_USE_SSL"
    value: "1"
  - name: "SENTRYDSN"
    value: ""
  - name: "DATABASE_URL"
    value: "<path:${vault_mount}/data/ixo-blocksync-core#DATABASE_URL>"
resources:
  requests:
    memory: 300Mi
    cpu: "100m"
  limits:
    memory: 700Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"