image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-guru-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
env:
  - name: "NODE_ENV"
    value: "development"
  - name: "SLACK_SIGNING_SECRET"
    value: "<path:${vault_mount}/data/ixo-guru#SLACK_SIGNING_SECRET>"
  - name: "SLACK_BOT_TOKEN"
    value: "<path:${vault_mount}/data/ixo-guru#SLACK_BOT_TOKEN>"
  - name: "BOT_OAUTH_TOKEN"
    value: "<path:${vault_mount}/data/ixo-guru#BOT_OAUTH_TOKEN>"
  - name: "USER_OAUTH_TOKEN"
    value: "<path:${vault_mount}/data/ixo-guru#USER_OAUTH_TOKEN>"
  - name: "SLACK_APP_LEVEL_TOKEN"
    value: "<path:${vault_mount}/data/ixo-guru#SLACK_APP_LEVEL_TOKEN>"
  - name: "API_KEY"
    value: "<path:${vault_mount}/data/ixo-guru#API_KEY>"
  - name: "QUEUE_CALLBACK_Root_Path"
    value: "<path:${vault_mount}/data/ixo-guru#QUEUE_CALLBACK_Root_Path>"
  - name: "QSTASH_URL"
    value: "<path:${vault_mount}/data/ixo-guru#QSTASH_URL>"
  - name: "QSTASH_TOKEN"
    value: "<path:${vault_mount}/data/ixo-guru#QSTASH_TOKEN>"
  - name: "QSTASH_CURRENT_SIGNING_KEY"
    value: "<path:${vault_mount}/data/ixo-guru#QSTASH_CURRENT_SIGNING_KEY>"
  - name: "QSTASH_NEXT_SIGNING_KEY"
    value: "<path:${vault_mount}/data/ixo-guru#QSTASH_NEXT_SIGNING_KEY>"
  - name: "REDIS_URL"
    value: "<path:${vault_mount}/data/ixo-guru#REDIS_URL>"
  - name: "AITABLE_BASE_TABLE_LINK"
    value: "<path:${vault_mount}/data/ixo-guru#AITABLE_BASE_TABLE_LINK>"
  - name: "AIRTABLE_API_KEY"
    value: "<path:${vault_mount}/data/ixo-guru#AIRTABLE_API_KEY>"
  - name: "AIRTABLE_BASE_ID"
    value: "<path:${vault_mount}/data/ixo-guru#AIRTABLE_BASE_ID>"
  - name: "OPENAI_API_KEY"
    value: "<path:${vault_mount}/data/ixo-guru#OPENAI_API_KEY>"
  - name: "PINECONE_API_KEY"
    value: "<path:${vault_mount}/data/ixo-guru#PINECONE_API_KEY>"
  - name: "PINECONE_INDEX"
    value: "<path:${vault_mount}/data/ixo-guru#PINECONE_INDEX>"
  - name: "LANGCHAIN_TRACING_V2"
    value: "<path:${vault_mount}/data/ixo-guru#LANGCHAIN_TRACING_V2>"
  - name: "LANGCHAIN_ENDPOINT"
    value: "<path:${vault_mount}/data/ixo-guru#LANGCHAIN_ENDPOINT>"
  - name: "LANGCHAIN_API_KEY"
    value: "<path:${vault_mount}/data/ixo-guru#LANGCHAIN_API_KEY>"
  - name: "LANGCHAIN_PROJECT"
    value: "<path:${vault_mount}/data/ixo-guru#LANGCHAIN_PROJECT>"
  - name: "TRAVEL_IMPACT_MODEL_API_KEY"
    value: "<path:${vault_mount}/data/ixo-guru#TRAVEL_IMPACT_MODEL_API_KEY>"
service:
  port: 3000
resources:
  requests:
    memory: 200Mi
    cpu: "50m"
  limits:
    memory: 350Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"