image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-jokes-oracle-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3000"
  - name: "CORS_ORIGIN"
    value: "*"
  - name: ORACLE_NAME
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#ORACLE_NAME>"
  - name: MATRIX_BASE_URL
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#MATRIX_BASE_URL>"
  - name: MATRIX_ORACLE_ADMIN_PASSWORD
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#MATRIX_ORACLE_ADMIN_PASSWORD>"
  - name: MATRIX_ORACLE_ADMIN_ACCESS_TOKEN
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#MATRIX_ORACLE_ADMIN_ACCESS_TOKEN>"
  - name: MATRIX_ORACLE_ADMIN_USER_ID
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#MATRIX_ORACLE_ADMIN_USER_ID>"
  - name: MATRIX_RECOVERY_PHRASE
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#MATRIX_RECOVERY_PHRASE>"
  - name: OPENAI_API_KEY
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#OPENAI_API_KEY>"
  - name: LANGFUSE_PUBLIC_KEY
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#LANGFUSE_PUBLIC_KEY>"
  - name: LANGFUSE_SECRET_KEY
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#LANGFUSE_SECRET_KEY>"
  - name: LANGFUSE_HOST
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#LANGFUSE_HOST>"
  - name: TAVILY_API_KEY
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#TAVILY_API_KEY>"
  - name: SLACK_BOT_OAUTH_TOKEN
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#SLACK_BOT_OAUTH_TOKEN>"
  - name: SLACK_APP_LEVEL_TOKEN
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#SLACK_APP_LEVEL_TOKEN>"
  - name: USER_SUBSCRIPTIONS_API_URL
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#USER_SUBSCRIPTIONS_API_URL>"
  - name: RPC_URL
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#RPC_URL>"
  - name: SECP_MNEMONIC
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#SECP_MNEMONIC>"
  - name: DID
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#DID>"
  - name: ORACLE_ACCOUNT_ADDRESS
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#ORACLE_ACCOUNT_ADDRESS>"
  - name: ORACLE_ENTITY_DID
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#ORACLE_ENTITY_DID>"
  - name: RELAYER_NODE
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#RELAYER_NODE>"
  - name: CHAIN_NETWORK
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#CHAIN_NETWORK>"
  - name: BLOCKSYNC_GRAPHQL_URL
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#BLOCKSYNC_GRAPHQL_URL>"
  - name: DENOM
    value: "<path:${vault_mount}/data/ixo-jokes-oracle#DENOM>"
  - name: CHROMA_URL
    value: "http://chromadb.chromadb.svc.cluster.local:8000"
service:
  port: 3000
resources:
  requests:
    memory: 200Mi
    cpu: "50m"
  limits:
    memory: 750Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"