image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-blocksync-core-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 8081
env:
  - name: "PORT"
    value: "8081"
  - name: "NODE_ENV"
    value: "production"
  - name: "TRUST_PROXY"
    value: "1"
  - name: "RPC"
    value: "https://${environment}.ixo.earth/rpc/"
  - name: "MIGRATE_DB_PROGRAMATICALLY"
    value: "1"
  - name: "DATABASE_USE_SSL"
    value: "1"
  - name: "SENTRYDSN"
    value: ""
  - name: "DATABASE_URL"
    value: "postgresql://${pgUsername}:${pgPassword}@${pgCluster}-primary.${pgNamespace}.svc.cluster.local/${pgUsername}"
resources:
  requests:
    memory: 300Mi
    cpu: "100m"
  limits:
    memory: 600Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"