image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-blocksync-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 8082
env:
  - name: "PORT"
    value: "8082"
  - name: "NODE_ENV"
    value: "production"
  - name: "RPC"
    value: "https://devnet.ixo.earth/rpc/"
  - name: "MIGRATE_DB_PROGRAMATICALLY"
    value: "1"
  - name: "DATABASE_USE_SSL"
    value: "1"
  - name: "IPFS_SERVICE_MAPPING"
    value: "https://devnet-blocksync-graphql.ixo.earth/api/ipfs/"
  - name: "DATABASE_URL_CORE"
    value: "postgresql://${pgUsername_core}:${pgPassword_core}@${pgCluster}-primary.${pgNamespace}.svc.cluster.local/${pgUsername_core}"
  - name: "DATABASE_URL"
    value: "postgresql://${pgUsername}:${pgPassword}@${pgCluster}-primary.${pgNamespace}.svc.cluster.local/${pgUsername}"
  - name: "ENTITY_MODULE_CONTRACT_ADDRESS"
    value: "ixo14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sqa3vn7"
resources:
  requests:
    memory: 300Mi
    cpu: "100m"
  limits:
    memory: 800Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"