image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-deeplink-server-nest-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 80
env:
  - name: "NODE_ENV"
    value: "production"
  - name: "AUTHORIZATION"
    value: "<path:${vault_mount}/data/ixo-deeplink-server#AUTHORIZATION>"
  - name: "DATABASE_URL"
    value: "postgresql://${pgUsername}:${pgPassword}@${pgCluster}-primary.${pgNamespace}.svc.cluster.local/${pgUsername}"
  - name: "BASE_URL"
    value: "<path:${vault_mount}/data/ixo-deeplink-server#BASE_URL>"
  - name: "REDIRECT_URL"
    value: "<path:${vault_mount}/data/ixo-deeplink-server#REDIRECT_URL>"
  - name: "ANDROID_REDIRECT_URL"
    value: "<path:${vault_mount}/data/ixo-deeplink-server#ANDROID_REDIRECT_URL>"
  - name: "IOS_REDIRECT_URL"
    value: "<path:${vault_mount}/data/ixo-deeplink-server#IOS_REDIRECT_URL>"
  - name: "FALLBACK_URL"
    value: "<path:${vault_mount}/data/ixo-deeplink-server#FALLBACK_URL>"
  - name: "MIGRATE_DB_PROGRAMATICALLY"
    value: "1"
  - name: "DATABASE_USE_SSL"
    value: "1"
  - name: "PORT"
    value: "80"
resources:
  requests:
    memory: 150Mi
    cpu: "50m"
  limits:
    memory: 250Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"