image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-kyc-server-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 3000
env:
  - name: "NODE_ENV"
    value: "production"
  - name: "AUTHORIZATION"
    value: "<path:${vault_mount}/data/ixo-kyc-server#AUTHORIZATION>"
  - name: "COMPLYCUBE_API_KEY"
    value: "<path:${vault_mount}/data/ixo-kyc-server#COMPLYCUBE_API_KEY>"
  - name: "COMPLYCUBE_WEBHOOK_SECRET"
    value: "<path:${vault_mount}/data/ixo-kyc-server#COMPLYCUBE_WEBHOOK_SECRET>"
  - name: "WEBVIEW_BASE_URL"
    value: "<path:${vault_mount}/data/ixo-kyc-server#WEBVIEW_BASE_URL>"
  - name: "IXO_NETWORK"
    value: "${environment}"
  - name: "ORACLE_DID"
    value: "<path:${vault_mount}/data/ixo-kyc-server#ORACLE_DID>"
  - name: "CREDENTIALS_WORKER_API_KEY"
    value: "<path:${vault_mount}/data/ixo-kyc-server#CREDENTIALS_WORKER_API_KEY>"
  - name: "CREDENTIALS_WORKER_URL"
    value: "<path:${vault_mount}/data/ixo-kyc-server#CREDENTIALS_WORKER_URL>"
  - name: "RPC_ENDPOINT"
    value: "${rpc_url}"
  - name: "ORACLE_DELEGATOR_ADDRESS"
    value: "<path:${vault_mount}/data/ixo-kyc-server#ORACLE_DELEGATOR_ADDRESS>"
  - name: "ORACLE_DELEGATE_MNEMONIC"
    value: "<path:${vault_mount}/data/ixo-kyc-server#ORACLE_DELEGATE_MNEMONIC>"
  - name: "NOTIFICATION_SERVER_API_KEY"
    value: "<path:${vault_mount}/data/ixo-kyc-server#NOTIFICATION_SERVER_API_KEY>"
  - name: "INVESTOR_EVALUATION_AUTHORIZATION"
    value: "<path:${vault_mount}/data/ixo-kyc-server#INVESTOR_EVALUATION_AUTHORIZATION>"
  - name: "SLACK_WEBHOOK_URL"
    value: "<path:${vault_mount}/data/ixo-kyc-server#SLACK_WEBHOOK_URL>"
  - name: "DATABASE_URL"
    value: "postgresql://${pgUsername}:${pgPassword}@${pgCluster}-primary.${pgNamespace}.svc.cluster.local/${pgUsername}"
  - name: "MIGRATE_DB_PROGRAMATICALLY"
    value: "1"
  - name: "DATABASE_USE_SSL"
    value: "1"
  - name: "PORT"
    value: "3000"
resources:
  requests:
    memory: 150Mi
    cpu: "50m"
  limits:
    memory: 250Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"