image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-faucet-nest-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 80
env:
  - name: "NODE_ENV"
    value: "production"
  - name: "RPC_ENDPOINT"
    value: "${rpc_url}"
  - name: "PORT"
    value: "80"
  - name: "FAUCET_MNEMONIC"
    value: "<path:${vault_mount}/data/ixo-faucet#FAUCET_MNEMONIC>"
  - name: "PROJECT_NAME"
    value: "Ixo ${title(environment)}"
resources:
  requests:
    memory: 300Mi
    cpu: "100m"
  limits:
    memory: 600Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"