image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-did-resolver-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 8080
env:
  - name: "NODE_ENV"
    value: "production"
  - name: "RPC_ENDPOINT"
    value: "${rpc_url}"
  - name: "PORT"
    value: "8080"
resources:
  requests:
    memory: 300Mi
    cpu: "100m"
  limits:
    memory: 600Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"