image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-observable-framework-builder-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
persistentVolume:
  storageClass: ${storage_class}
  size: ${storage_size}
service:
  port: 3000
env:
  - name: "PORT"
    value: "3000"
  - name: "API_KEY"
    value: "<path:${vault_mount}/data/ixo-observable-framework-builder#API_KEY>"
  - name: "DATABASE_URL"
    value: "postgresql://${pgUsername}:${pgPassword}@${pgCluster}-primary.${pgNamespace}.svc.cluster.local/${pgUsername}"
  - name: "DATABASE_USE_SSL"
    value: "1"
  - name: "MIGRATE_DB_PROGRAMATICALLY"
    value: "1"
  - name: "TRUST_PROXY"
    value: "1"
  - name: "CORS_ORIGIN"
    value: "*"
  - name: "NODE_ENV"
    value: "production"
resources:
  requests:
    memory: 100Mi
    cpu: "40m"
  limits:
    memory: 1024Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"