image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-payments-nest-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
service:
  port: 3000
env:
  - name: "NODE_ENV"
    value: "production"
  - name: "RPC_URL"
    value: "${rpc_url}"
  - name: "MIGRATE_DB_PROGRAMATICALLY"
    value: "1"
  - name: "DATABASE_USE_SSL"
    value: "1"
  - name: "PORT"
    value: "3000"
  - name: "DATABASE_URL"
    value: "postgresql://${pgUsername}:${pgPassword}@${pgCluster}-primary.${pgNamespace}.svc.cluster.local/${pgUsername}"
  - name: "AUTHORIZATION"
    value: "<path:${vault_mount}/data/ixo-payments-nest#AUTHORIZATION>"
  - name: "BLOCKSYNC_URL"
    value: "<path:${vault_mount}/data/ixo-payments-nest#BLOCKSYNC_URL>"
  - name: "STRIPE_API_KEY"
    value: "<path:${vault_mount}/data/ixo-payments-nest#STRIPE_API_KEY>"
  - name: "STRIPE_WEBHOOK_SECRET"
    value: "<path:${vault_mount}/data/ixo-payments-nest#STRIPE_WEBHOOK_SECRET>"
  - name: "NOTIFICATIONS_WORKER_URL"
    value: "<path:${vault_mount}/data/ixo-payments-nest#NOTIFICATIONS_WORKER_URL>"
  - name: "NOTIFICATIONS_WORKER_AUTH"
    value: "<path:${vault_mount}/data/ixo-payments-nest#NOTIFICATIONS_WORKER_AUTH>"
  - name: "MNEMONIC"
    value: "<path:${vault_mount}/data/ixo-payments-nest#MNEMONIC>"
  - name: "NETWORK"
    value: "<path:${vault_mount}/data/ixo-payments-nest#NETWORK>"
  - name: "CRYPTOCOM_WEBHOOK_SECRET"
    value: "<path:${vault_mount}/data/ixo-payments-nest#CRYPTOCOM_WEBHOOK_SECRET>"
  - name: "SENTRY_DSN"
    value: "<path:${vault_mount}/data/ixo-payments-nest#SENTRY_DSN>"
  - name: "COLLECTIONS_TO_SELL"
    value: "<path:${vault_mount}/data/ixo-payments-nest#COLLECTIONS_TO_SELL>"
  - name: "COLLECTIONS_TO_SELL_END_DATE_ADD_MONTHS"
    value: "<path:${vault_mount}/data/ixo-payments-nest#COLLECTIONS_TO_SELL_END_DATE_ADD_MONTHS>"
  - name: "TOKENS_TO_SELL"
    value: "<path:${vault_mount}/data/ixo-payments-nest#TOKENS_TO_SELL>"
  - name: "TOKENS_TO_SELL_COLLECTIONS"
    value: "<path:${vault_mount}/data/ixo-payments-nest#TOKENS_TO_SELL_COLLECTIONS>"
resources:
  requests:
    memory: 300Mi
    cpu: "40m"
  limits:
    memory: 600Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"