image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
persistentVolume:
  storageClass: ${storage_class}
  size: ${storage_size}
service:
  port: 8081
env:
  - name: "PORT"
    value: "8081"
resources:
  requests:
    memory: 150Mi
    cpu: "40m"
  limits:
    memory: 300Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"
backup:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi
  gcs:
    bucket: ${gcs_bucket}
config:
  homeserverUrl: https://matrix.supamoto.global
  homeserverName: matrix.supamoto.global
  ucan:
    hostname: rooms.bot.matrix.supamoto.global
registration:
  hs_token: "<path:ixo_core/data/matrix#MATRIX_SUPAMOTO_APPSERVICE_ROOMS_HS_TOKEN>"
  as_token: "<path:ixo_core/data/matrix#MATRIX_SUPAMOTO_APPSERVICE_ROOMS_AS_TOKEN>"
  url: http://supamoto-matrix-appservice-rooms.matrix-synapse.svc.cluster.local:9000