image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
persistentVolume:
  storageClass: ${storage_class}
  size: ${storage_size}
service:
  port: 8083
env:
  - name: "PORT"
    value: "8083"
resources:
  requests:
    memory: 100Mi
    cpu: "40m"
  limits:
    memory: 200Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"
backup:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi
  gcs:
    bucket: ${gcs_bucket}
config:
  homeserverUrl: https://matrix.supamoto.global
  homeserverName: matrix.supamoto.global
  accessToken: "<path:ixo_core/data/matrix#MATRIX_SUPAMOTO_BIDS_BOT_ACCESS_TOKEN>"
  ucan:
    hostname: bids.bot.matrix.supamoto.global