---
# ========== SYSTEMS ==========
# Main Infrastructure System
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ixo-infrastructure
  description: IXO Terra Infrastructure - Complete cloud-native platform
  annotations:
    github.com/project-slug: ixofoundation/ixo-terra-infra
    backstage.io/source-location: url:https://github.com/ixofoundation/ixo-terra-infra
  tags:
    - infrastructure
    - platform
    - kubernetes
spec:
  owner: infrastructure-team

---
# IXO Core Applications System
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ixo-core-applications
  description: Core IXO blockchain and application services
  tags:
    - ixo
    - blockchain
    - applications
    - core
spec:
  owner: core-team

---
# Communication System
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: communication-platform
  description: Matrix-based communication and collaboration platform
  tags:
    - communication
    - matrix
    - collaboration
spec:
  owner: platform-team

---
# Data Platform System
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: data-platform
  description: Databases, storage, and data processing infrastructure
  tags:
    - data
    - databases
    - storage
spec:
  owner: data-team

---
# Monitoring & Observability System
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: observability-platform
  description: Monitoring, logging, and observability infrastructure
  tags:
    - monitoring
    - observability
    - metrics
    - logging
spec:
  owner: infrastructure-team

---
# Security Platform System
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: security-platform
  description: Security, authentication, and secrets management
  tags:
    - security
    - authentication
    - secrets
spec:
  owner: security-team

---
# ========== INFRASTRUCTURE COMPONENTS ==========
# Ghost Blog/CMS Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ghost-cms
  description: IXO Blog and Content Management System
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ghost'
    backstage.io/kubernetes-namespace: ghost
    argocd/app-name: ghost
    backstage.io/techdocs-ref: dir:.
  tags:
    - cms
    - blog
    - content
  links:
    - url: https://ghost.org/docs/
      title: Ghost Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: content-team
  system: ixo-infrastructure
  dependsOn:
    - component:postgres-operator

---
# Matrix Server Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: matrix-server
  description: Matrix homeserver for secure communications
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=synapse'
    backstage.io/kubernetes-namespace: matrix-synapse
    argocd/app-name: matrix
  tags:
    - communication
    - matrix
    - synapse
    - messaging
  links:
    - url: https://matrix-org.github.io/synapse/
      title: Synapse Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: communication-platform
  dependsOn:
    - component:postgres-operator
    - component:vault

---
# Matrix Livekit Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: matrix-livekit
  description: Real-time video/audio service for Matrix
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=livekit'
    backstage.io/kubernetes-namespace: matrix-livekit
    argocd/app-name: matrix-livekit
  tags:
    - communication
    - video
    - audio
    - realtime
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: communication-platform
  dependsOn:
    - component:matrix-server

---
# Matrix Slack Bridge
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: matrix-slack-bridge
  description: Bridge between Matrix and Slack
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=matrix-slack'
    backstage.io/kubernetes-namespace: matrix-synapse
    argocd/app-name: matrix-slack
  tags:
    - communication
    - bridge
    - slack
    - integration
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: communication-platform
  dependsOn:
    - component:matrix-server

---
# Matrix Admin Interface
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: matrix-admin
  description: Administrative interface for Matrix server
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=matrix-admin'
    backstage.io/kubernetes-namespace: matrix-synapse
    argocd/app-name: matrix-admin
  tags:
    - communication
    - admin
    - management
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: communication-platform
  dependsOn:
    - component:matrix-server

---
# Backstage Developer Portal
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Developer portal and service catalog
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=backstage'
    backstage.io/kubernetes-namespace: backstage
    argocd/app-name: backstage
  tags:
    - developer-portal
    - catalog
    - platform
  links:
    - url: https://backstage.io/docs/
      title: Backstage Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: ixo-infrastructure
  dependsOn:
    - component:postgres-operator

---
# Vault Secrets Management
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vault
  description: HashiCorp Vault for secrets management
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=vault'
    backstage.io/kubernetes-namespace: vault
    argocd/app-name: vault
  tags:
    - security
    - secrets
    - vault
  links:
    - url: https://developer.hashicorp.com/vault/docs
      title: Vault Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: security-team
  system: security-platform

---
# Prometheus Monitoring
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus
  description: Metrics collection and monitoring
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=prometheus'
    backstage.io/kubernetes-namespace: prometheus
    argocd/app-name: prometheus
  tags:
    - monitoring
    - metrics
    - alerting
  links:
    - url: https://prometheus.io/docs/
      title: Prometheus Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: infrastructure-team
  system: observability-platform

---
# Loki Logging
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loki
  description: Log aggregation and storage
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=loki'
    backstage.io/kubernetes-namespace: ixo-loki
    argocd/app-name: loki
  tags:
    - logging
    - aggregation
    - storage
spec:
  type: service
  lifecycle: production
  owner: infrastructure-team
  system: observability-platform

---
# Uptime Kuma Monitoring
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: uptime-kuma
  description: Uptime monitoring and status page
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=uptime-kuma'
    backstage.io/kubernetes-namespace: uptime-kuma
    argocd/app-name: uptime-kuma
  tags:
    - monitoring
    - uptime
    - status-page
  links:
    - url: https://github.com/louislam/uptime-kuma
      title: Uptime Kuma Repository
      icon: github
spec:
  type: service
  lifecycle: production
  owner: infrastructure-team
  system: observability-platform

---
# PostgreSQL Operator
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgres-operator
  description: PostgreSQL database operator and clusters
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=postgres-operator'
    backstage.io/kubernetes-namespace: postgres-operator
    argocd/app-name: postgres-operator
  tags:
    - database
    - postgresql
    - operator
  links:
    - url: https://postgres-operator.readthedocs.io/
      title: PostgreSQL Operator Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: data-team
  system: data-platform

---
# Neo4j Graph Database
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: neo4j
  description: Graph database for relationship data
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=neo4j'
    backstage.io/kubernetes-namespace: neo4j
    argocd/app-name: neo4j
  tags:
    - database
    - graph
    - neo4j
  links:
    - url: https://neo4j.com/docs/
      title: Neo4j Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: data-team
  system: data-platform

---
# ChromaDB Vector Database
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chromadb
  description: Vector database for AI/ML workloads
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=chromadb'
    backstage.io/kubernetes-namespace: chromadb
    argocd/app-name: chromadb
  tags:
    - database
    - vector
    - ai
    - ml
  links:
    - url: https://docs.trychroma.com/
      title: ChromaDB Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: ai-team
  system: data-platform

---
# NGINX Ingress Controller
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx-ingress
  description: NGINX Ingress Controller for traffic routing
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ingress-nginx'
    backstage.io/kubernetes-namespace: ingress-nginx
    argocd/app-name: nginx-ingress
  tags:
    - ingress
    - traffic
    - routing
    - nginx
spec:
  type: service
  lifecycle: production
  owner: infrastructure-team
  system: ixo-infrastructure

---
# Cert Manager
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cert-manager
  description: Automatic TLS certificate management
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=cert-manager'
    backstage.io/kubernetes-namespace: cert-manager
    argocd/app-name: cert-manager
  tags:
    - security
    - tls
    - certificates
    - automation
spec:
  type: service
  lifecycle: production
  owner: security-team
  system: security-platform

---
# External DNS
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-dns
  description: Automatic DNS record management
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=external-dns'
    backstage.io/kubernetes-namespace: external-dns
    argocd/app-name: external-dns
  tags:
    - dns
    - automation
    - networking
spec:
  type: service
  lifecycle: production
  owner: infrastructure-team
  system: ixo-infrastructure

---
# Dex Identity Provider
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dex
  description: OpenID Connect identity provider
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=dex'
    backstage.io/kubernetes-namespace: dex
    argocd/app-name: dex
  tags:
    - security
    - authentication
    - oidc
    - identity
spec:
  type: service
  lifecycle: production
  owner: security-team
  system: security-platform

---
# ========== IXO CORE APPLICATIONS ==========
# IXO Cellnode
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-cellnode
  description: IXO blockchain node and RPC endpoint
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-cellnode'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-cellnode
  tags:
    - blockchain
    - node
    - rpc
    - cosmos
  links:
    - url: https://github.com/ixofoundation/ixo-blockchain
      title: IXO Blockchain Repository
      icon: github
spec:
  type: service
  lifecycle: production
  owner: core-team
  system: ixo-core-applications
  dependsOn:
    - component:postgres-operator
    - component:vault

---
# IXO Blocksync Core
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-blocksync-core
  description: Core blockchain synchronization service
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-blocksync-core'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-blocksync-core
  tags:
    - blockchain
    - sync
    - indexing
spec:
  type: service
  lifecycle: production
  owner: core-team
  system: ixo-core-applications
  dependsOn:
    - component:ixo-cellnode
    - component:postgres-operator
    - component:vault

---
# IXO Blocksync
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-blocksync
  description: Enhanced blockchain synchronization with IPFS integration
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-blocksync'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-blocksync
  tags:
    - blockchain
    - sync
    - ipfs
    - indexing
spec:
  type: service
  lifecycle: production
  owner: core-team
  system: ixo-core-applications
  dependsOn:
    - component:ixo-blocksync-core
    - component:postgres-operator
    - component:vault

---
# IXO Memory Engine
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-memory-engine
  description: AI memory and knowledge management engine
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-memory-engine'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-memory-engine
  tags:
    - ai
    - memory
    - knowledge
    - nlp
spec:
  type: service
  lifecycle: production
  owner: ai-team
  system: ixo-core-applications
  dependsOn:
    - component:chromadb
    - component:vault

---
# IXO Companion
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-companion
  description: AI-powered assistant and companion service
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-companion'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-companion
  tags:
    - ai
    - assistant
    - companion
    - chat
spec:
  type: service
  lifecycle: production
  owner: ai-team
  system: ixo-core-applications
  dependsOn:
    - component:ixo-memory-engine
    - component:vault

---
# IXO DID Resolver
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-did-resolver
  description: Decentralized identifier resolution service
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-did-resolver'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-did-resolver
  tags:
    - did
    - identity
    - resolver
    - blockchain
spec:
  type: service
  lifecycle: production
  owner: core-team
  system: ixo-core-applications
  dependsOn:
    - component:ixo-cellnode
    - component:vault

---
# IXO Faucet
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-faucet
  description: Token faucet for testnet distributions
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-faucet'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-faucet
  tags:
    - faucet
    - tokens
    - testnet
spec:
  type: service
  lifecycle: production
  owner: core-team
  system: ixo-core-applications
  dependsOn:
    - component:ixo-cellnode
    - component:vault

---
# IXO KYC Server
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-kyc-server
  description: Know Your Customer verification service
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-kyc-server'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-kyc-server
  tags:
    - kyc
    - verification
    - compliance
spec:
  type: service
  lifecycle: production
  owner: compliance-team
  system: ixo-core-applications
  dependsOn:
    - component:postgres-operator
    - component:vault

---
# IXO Payments Nest
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-payments-nest
  description: Payment processing and management service
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-payments-nest'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-payments-nest
  tags:
    - payments
    - processing
    - finance
spec:
  type: service
  lifecycle: production
  owner: finance-team
  system: ixo-core-applications
  dependsOn:
    - component:postgres-operator
    - component:vault

---
# IXO Notification Server
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-notification-server
  description: Centralized notification and alerting service
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-notification-server'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-notification-server
  tags:
    - notifications
    - alerts
    - messaging
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: ixo-core-applications
  dependsOn:
    - component:postgres-operator
    - component:vault

---
# IXO Message Relayer
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ixo-message-relayer
  description: Inter-blockchain communication message relayer
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=ixo-message-relayer'
    backstage.io/kubernetes-namespace: core
    argocd/app-name: ixo-message-relayer
  tags:
    - ibc
    - relayer
    - blockchain
    - communication
spec:
  type: service
  lifecycle: production
  owner: core-team
  system: ixo-core-applications
  dependsOn:
    - component:ixo-cellnode
    - component:postgres-operator
    - component:vault 