apiVersion: v1
kind: Pod
metadata:
  name: devops-filebrowser
  namespace: core
  labels:
    app: devops-filebrowser
spec:
  containers:
    - name: filebrowser
      image: filebrowser/filebrowser:latest
      args:
        - "--port"
        - "8080"
      ports:
        - containerPort: 8080
          name: http
      volumeMounts:
        - name: common-storage
          mountPath: /srv
      securityContext:
        runAsUser: 0
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
  volumes:
    - name: common-storage
      persistentVolumeClaim:
        claimName: ${ORG}-core-common-storage  # Replace ${ORG} with your organization name



