image:
  allowReset: true
  persistDirectory: /index-data
  repository: chromadb/chroma
  apiVersion: "latest"
  base: ""

chromadb:
  auth:
    enabled: false
  data:
    volumeSize: 40Gi
    storageClass: ${storage_class}
    retentionPolicyOnDelete: Retain

resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    memory: 600Mi