ingress:
  enabled: true
  className: nginx
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ${app_name}-tls
  hosts:
    - host: ${host}
      paths:
        - path: /${app_name}(/|$)(.*)
          pathType: ImplementationSpecific
service:
  port: 5000
env:
  - name: PORT
    value: '5000'
  - name: WEB3_KEY
    value: <path:${kv_mount}/data/${app_name}#WEB3_KEY>
  - name: WEB3_PROOF
    value: <path:${kv_mount}/data/${app_name}#WEB3_PROOF>
  - name: DATABASE_URL
    value: ${DB_ENDPOINT}
resources:
  requests:
    memory: 100Mi
    cpu: "100m"
  limits:
    memory: 200Mi