image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ${app_name}-tls
  hosts:
    - host: ${host}
      paths:
        - path: ${ingressPath}
          pathType: ImplementationSpecific
service:
  port: ${port}
env:
  ${indent(2, yamlencode(envVars))}
resources:
  requests:
    memory: ${memoryRequest}
    cpu: "100m"
  limits:
    memory: ${memoryLimit}
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"