name: ${app_name}
image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ${app_name}-tls
  hosts:
    - host: ${host}
      paths:
        - path: ${ingressPath}
          pathType: Exact
service:
  port: ${port}
env:
  ${indent(2, join("\n", [for v in envVars : "- name: \"${v.name}\"\n  value: \"${v.value}\""]))}
resources:
  requests:
    memory: ${memoryRequest}
    cpu: "100m"
  limits:
    memory: ${memoryLimit}
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"