config:
  matrix_slack:
    homeserver:
      domain: ${domain}
    appservice:
      database:
        uri: ${postgresUri}
    bridge:
      permissions:
        "*": relay
        "${domain}": user
        "@admin:${domain}": admin