replicaCount: 2
persistence:
  enabled: true
  storageClass: "vultr-block-storage-hdd"
  size: 200Gi
resources:
   limits:
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi
storageClass:
  mountOptions:
    - tcp
    - vers=4.1
affinity:
  podAntiAffinity:  # Spread the pods across nodes for high availability
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - nfs-server-provisioner
        topologyKey: "kubernetes.io/hostname"