replicaCount: 2
persistence:
  enabled: true
  storageClass: ${storage_class}
  size: 200Gi
resources:
   limits:
     memory: 512Mi
   requests:
     cpu: 250m
     memory: 256Mi
storageClass:
  mountOptions:
    - tcp
    - vers=4.1
extraArgs:
  device-based-fsids: false
affinity:
  podAntiAffinity:  # Spread the pods across nodes for high availability
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - nfs-server-provisioner
        topologyKey: "kubernetes.io/hostname"