apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: ${pg_cluster_name}
  namespace: ${pg_namespace}
spec:
  shutdown: false
  image: ${pg_image}:${pg_image_tag}
  postgresVersion: ${pg_version}
  service:
    metadata:
      annotations:
        tailscale.com/expose: "true"
  monitoring:
    pgmonitor:
      exporter:
        image: ${pgmonitoring_image}:${pgmonitoring_image_tag}
        configuration:
          - configMap:
              name: promtail-config
              optional: true
          - configMap:
              name: ${pg_cluster_name}-exporter-queries-config
  users:
    ${indent(4, pg_users)}
  instances:
    ${indent(4, pg_instances)}
  backups:
    pgbackrest:
      image: ${pgbackrest_image}:${pgbackrest_image_tag}
      global:
        repo1-gcs-key: /etc/pgbackrest/conf.d/gcs-key.json
      configuration:
        - secret:
            name: ${pg_cluster_name}-gcs-pgbackrest-secret
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        ${indent(8, pgbackrest_repos)}
  databaseInitSQL:
    key: init.sql
    name: ${pg_cluster_name}-init-sql
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          log_checkpoints: 'on'
          log_statement: 'mod'
          log_line_prefix: '%t [%p]: host=%h user=%u,db=%d '
          log_lock_waits: 'on'
          logging_collector: 'on'
      bootstrap:
        initdb:
          - locale: C
          - encoding: C