apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: ${pg_cluster_name}
  namespace: ${pg_namespace}
spec:
  image: ${pg_image}:${pg_image_tag}
  postgresVersion: ${pg_version}
  service:
    metadata:
      annotations:
        tailscale.com/expose: "true"
  monitoring:
    pgmonitor:
      exporter:
        image: ${pgmonitoring_image}:${pgmonitoring_image_tag}
  users:
    ${indent(4, pg_users)}
  instances:
    ${indent(4, pg_instances)}
  backups:
    pgbackrest:
      image: ${pgbackrest_image}:${pgbackrest_image_tag}
      repos:
        ${indent(8, pgbackrest_repos)}
  databaseInitSQL:
    key: init.sql
    name: ${pg_cluster_name}-init-sql
  patroni:
    dynamicConfiguration:
      bootstrap:
        initdb:
          - locale: C
          - encoding: C