- name: ixo-postgresql-0
  replicas: 2
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
  dataVolumeClaimSpec:
    storageClassName: "vultr-block-storage"
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: 40Gi