- name: ixo-postgresql-0
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 2Gi
  dataVolumeClaimSpec:
    storageClassName: "vultr-block-storage"
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: 40Gi