apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${name}
  namespace: ${argo_namespace}
spec:
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data
  destination:
    namespace: ${namespace}
    server: https://kubernetes.default.svc
  project: default
  source:
    plugin:
      name: avp
      env:
        - name: HELM_VALUES
          value: |
            ${indent(12, helm_values)}
    path: ${path}
    repoURL: ${repository}
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true