apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${name}
  namespace: ${argo_namespace}
spec:
  destination:
    namespace: ${namespace}
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        ${indent(8, helm_values)}
      valueFiles:
        - values.yaml
    path: ${path}
    repoURL: ${repository}
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true