apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${name}
  namespace: ${argo_namespace}
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  source:
    chart: ${chart}
    repoURL: ${repository}
    enableOCI: ${isOci}
    targetRevision: ${revision}
    helm:
      releaseName: ${chart}
      values: |
        ${indent(8, helm_values)}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${namespace}