apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-slack.fullname" . }}-config
  labels:
    {{- include "matrix-slack.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ .Files.Get "config.yaml" | indent 4 | nindent 4 }}