apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-slack.fullname" . }}
  labels:
    {{- include "matrix-slack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 29335
      targetPort: appservice
      protocol: TCP
      name: appservice
  selector:
    {{- include "matrix-slack.selectorLabels" . | nindent 4 }}
