{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "matrix-livekit.fullname" . }}
  labels:
    {{- include "matrix-livekit.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "matrix-livekit.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress:
    - {} # Allow all egress by default
  {{- end }}
{{- end }} 