{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-livekit.secretName" . }}
  labels:
    {{- include "matrix-livekit.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.data }}
  {{- range $key, $value := .Values.secrets.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  {{- else if and .Values.livekit.key .Values.livekit.secret }}
  livekit-key: {{ .Values.livekit.key | b64enc }}
  livekit-secret: {{ .Values.livekit.secret | b64enc }}
  {{- end }}
{{- end }} 